#'@include 1-sampling-functions.R
NULL

# Resampling Functions ---------------------------------------------------------

## Repeated Sampling -----------------------------------------------------------

#' Repeated Samples
#'
#'@description Takes repeated samples from the population by using the provided
#'sampling function.
#'
#'@param k integer, the number of repeated samples to generate
#'@param sampleFun the sampling function
#'@param ... further arguments to \code{sampleFun}
#'
#'@return A list of length \code{k} where each element
#'is a vector of indices representing the sampled data.
#'
#'@author Alessandro Barberis
#'
#'@examples \dontrun{
#'#set seed for reproducibility
#'set.seed(seed = 5381L)
#'
#'#Take two samples without replacement
#'repeatedSample(
#'  k = 2,
#'  sampleFun = sampleWithoutReplacement,
#'  N = 10,
#'  n = 5
#')
#'}
#'@keywords internal
repeatedSample <- function(
    k = 1,
    sampleFun,
    ...
  ){

  #convert
  k = as.integer(k)

  #args
  args = list(...)

  #sample
  out = replicate(
    n = k,
    expr = do.call(what = sampleFun, args = args),
    simplify = F)

  #return
  return(out)
}

#'Repeated k-1 folds
#'
#'@description Takes a population assigned to k folds and return a list of k
#'unique samples made of elements from k-1 folds.
#'
#'@param foldid vector of k fold ids
#'
#'@return A list of length \code{k} where each element is a vector
#'containing the indices of the sampled data.
#'
#'@details A list of length k is created from the folds, so that the i-th
#'item of the list is a vector of indices generated by removing the i-th fold
#'and merging the remaining k - 1 folds together.
#'
#'@author Alessandro Barberis
#'
#'@examples \dontrun{
#'#set seed for reproducibility
#'set.seed(seed = 5381L)
#'
#'#Assign data to 3 folds
#'repeatedKm1Folds(
#'  foldid = randomKFolds(N = 10, k = 3)
#')
#'}
#'
#'@keywords internal
repeatedKm1Folds <- function(
    foldid
  ){
  #sample
  ##get max fold id
  nfolds = max(foldid, na.rm = T)

  ##out list
  out = list()

  ##loop over and keep only the training sets
  for(i in seq(nfolds)){
    keep = !is.na(foldid) & foldid != i

    out[[i]] = which(keep)
  }

  #removed data
  if(isTRUE(any(is.na(foldid)))){
    attr(x = out, which = "removed.data") = which(is.na(foldid))
  }

  #return
  return(out)
}

### Resample Without Replacement -----------------------------------------------

#'Repeated Random Samples
#'
#'@description Takes repeated samples without replacement from the population.
#'See the **Details** section below for further information.
#'
#'@inheritParams repeatedSample
#'@inheritParams sampleWithoutReplacement
#'
#'@inherit repeatedSample return
#'
#'@details This function takes repeated samples by using the \code{\link{replicate}}
#'function and the \code{\link{sampleWithoutReplacement}} sampling
#'function.
#'
#'@author Alessandro Barberis
#'
#'@seealso
#'[`sampleWithoutReplacement`]
#'
#'@examples
#'#Set seed for reproducibility
#'set.seed(seed = 5381L)
#'
#'#Take two samples without replacement
#'repeatedSampleWithoutReplacement(
#'  k = 2,
#'  N = 10,
#'  n = 6
#')
#'
#'@export
repeatedSampleWithoutReplacement <- function(
    k,
    N,
    n,
    prob = NULL
  ){
  #check input
  isValid = isValidSampleInput(N = N, n = n, prob = prob, replace = F)
  if(isFALSE(isTRUE(isValid))){
    stop(paste(isValid, collapse = "\n"))
  }
  #compute
  out = repeatedSample(
    k = k,
    sampleFun = sampleWithoutReplacement,
    N = N,
    n = n,
    prob = prob
  )
  #return
  return(out)
}

#'Repeated Random Samples
#'
#'@description Takes repeated samples without replacement from the population.
#'See the **Details** section below for further information.
#'
#'@inheritParams repeatedSample
#'@inheritParams simpleRandomSampleWithoutReplacement
#'
#'@inherit repeatedSample return
#'
#'@details This function takes repeated samples by using the \code{\link{replicate}}
#'function and the \code{\link{simpleRandomSampleWithoutReplacement}} sampling
#'function.
#'
#'@author Alessandro Barberis
#'
#'@seealso
#'[`simpleRandomSampleWithoutReplacement`]
#'
#'@examples
#'#Set seed for reproducibility
#'set.seed(seed = 5381L)
#'
#'#Take two samples without replacement
#'repeatedSimpleRandomSampleWithoutReplacement(
#'  k = 2,
#'  N = 10,
#'  n = 6
#')
#'
#'@export
repeatedSimpleRandomSampleWithoutReplacement <- function(
    k,
    N,
    n
){
  #check input
  isValid = isValidSampleInput(N = N, n = n, replace = F)
  if(isFALSE(isTRUE(isValid))){
    stop(paste(isValid, collapse = "\n"))
  }
  #compute
  out = repeatedSample(
    k = k,
    sampleFun = simpleRandomSampleWithoutReplacement,
    N = N,
    n = n
  )
  #return
  return(out)
}

#'Repeated Permutation Samples
#'
#'@description Takes repeated samples without replacement from the population.
#'See the **Details** section below for further information.
#'
#'@inheritParams repeatedSample
#'@inheritParams sampleWithoutReplacement
#'
#'@inherit repeatedSample return
#'
#'@details This function takes repeated samples by using the \code{\link{replicate}}
#'function and the \code{\link{permutationSample}} sampling
#'function.
#'
#'@author Alessandro Barberis
#'
#'@seealso
#'[`permutationSample`]
#'
#'@examples
#'#Set seed for reproducibility
#'set.seed(seed = 5381L)
#'
#'#Take two samples without replacement
#'repeatedPermutationSample(
#'  k = 2,
#'  N = 10
#')
#'
#'@export
repeatedPermutationSample <- function(
    k,
    N
){
  #check input
  isValid = isValidSampleInput(N = N, replace = F)
  if(isFALSE(isTRUE(isValid))){
    stop(paste(isValid, collapse = "\n"))
  }
  #compute
  out = repeatedSample(
    k = k,
    sampleFun = permutationSample,
    N = N
  )
  #return
  return(out)
}

#'Repeated Stratified Random Samples
#'
#'@description Takes repeated stratified samples without replacement from the
#'population.
#'See the **Details** section below for further information.
#'
#'@inheritParams repeatedSample
#'@inheritParams stratifiedSampleWithoutReplacement
#'
#'@inherit repeatedSample return
#'
#'@details This function takes repeated samples by using the \code{\link{replicate}}
#'function and the \code{\link{stratifiedSampleWithoutReplacement}} sampling
#'function.
#'
#'@author Alessandro Barberis
#'
#'@seealso
#'[`stratifiedSampleWithoutReplacement`]
#'
#'@examples
#'#Set seed for reproducibility
#'set.seed(seed = 5381L)
#'
#'#Define strata
#'strata = c(rep("a", 3),rep("b", 6))
#'
#'#Check ratio
#'table(strata)/length(strata)
#'
#'#Stratified random samples
#'i = repeatedStratifiedSampleWithoutReplacement(
#'   k = 2,
#'   strata = strata,
#'   n = 3,
#')
#'#Check ratio
#'table(strata[i[[1]]])/length(strata[i[[1]]])
#'table(strata[i[[2]]])/length(strata[i[[2]]])
#'
#'@export
repeatedStratifiedSampleWithoutReplacement <- function(
    k,
    strata,
    n,
    prob = NULL
){
  #check input
  isValid = isValidStratifiedSampleInput(strata = strata, n = n, prob = prob, replace = F)
  if(isFALSE(isTRUE(isValid))){
    stop(paste(isValid, collapse = "\n"))
  }
  #compute
  out = repeatedSample(
    k = k,
    sampleFun = stratifiedSampleWithoutReplacement,
    strata = strata,
    n = n,
    prob = prob
  )
  #return
  return(out)
}

#'Repeated Balanced Random Samples
#'
#'@description Takes repeated balanced samples without replacement from the
#'population.
#'See the **Details** section below for further information.
#'
#'@inheritParams repeatedSample
#'@inheritParams balancedSampleWithoutReplacement
#'
#'@inherit repeatedSample return
#'
#'@details This function takes repeated samples by using the \code{\link{replicate}}
#'function and the \code{\link{balancedSampleWithoutReplacement}} sampling
#'function.
#'
#'@author Alessandro Barberis
#'
#'@seealso
#'[`balancedSampleWithoutReplacement`]
#'
#'@examples
#'#Set seed for reproducibility
#'set.seed(seed = 5381L)
#'
#'#Define strata
#'strata = c(rep("a", 3),rep("b", 6))
#'
#'#Check ratio
#'table(strata)/length(strata)
#'
#'#Balanced random samples
#'i = repeatedBalancedSampleWithoutReplacement(
#'   k = 2,
#'   strata = strata,
#'   n = 6
#')
#'#Check ratio
#'table(strata[i[[1]]])/length(strata[i[[1]]])
#'table(strata[i[[2]]])/length(strata[i[[2]]])
#'
#'@export
repeatedBalancedSampleWithoutReplacement <- function(
    k,
    strata,
    n,
    prob = NULL
){
  #check input
  isValid = isValidStratifiedSampleInput(strata = strata, n = n, prob = prob, replace = F)
  if(isFALSE(isTRUE(isValid))){
    stop(paste(isValid, collapse = "\n"))
  }
  #compute
  out = repeatedSample(
    k = k,
    sampleFun = balancedSampleWithoutReplacement,
    strata = strata,
    n = n,
    prob = prob
  )
  #return
  return(out)
}

### Resample With Replacement --------------------------------------------------

#'Repeated Random Samples With Replacement
#'
#'@description Takes repeated samples with replacement from the population.
#'See the **Details** section below for further information.
#'
#'@inheritParams repeatedSample
#'@inheritParams sampleWithReplacement
#'
#'@inherit repeatedSample return
#'
#'@details This function takes repeated samples by using the \code{\link{replicate}}
#'function and the \code{\link{sampleWithReplacement}} sampling
#'function.
#'
#'@author Alessandro Barberis
#'
#'@seealso
#'[`sampleWithReplacement`]
#'
#'@examples
#'#Set seed for reproducibility
#'set.seed(seed = 5381L)
#'
#'#Take two samples with replacement
#'repeatedSampleWithReplacement(
#'  k = 2,
#'  N = 10,
#'  n = 6
#')
#'
#'@export
repeatedSampleWithReplacement <- function(
    k,
    N,
    n,
    prob = NULL
){
  #check input
  isValid = isValidSampleInput(N = N, n = n, prob = prob, replace = T)
  if(isFALSE(isTRUE(isValid))){
    stop(paste(isValid, collapse = "\n"))
  }
  #compute
  out = repeatedSample(
    k = k,
    sampleFun = sampleWithReplacement,
    N = N,
    n = n,
    prob = prob
  )
  #return
  return(out)
}

#'Repeated Simple Random Samples With Replacement
#'
#'@description Takes repeated simple random samples with replacement from the
#'population.
#'See the **Details** section below for further information.
#'
#'@inheritParams repeatedSample
#'@inheritParams sampleWithReplacement
#'
#'@inherit repeatedSample return
#'
#'@details This function takes repeated samples by using the \code{\link{replicate}}
#'function and the \code{\link{simpleRandomSampleWithReplacement}} sampling
#'function.
#'
#'@author Alessandro Barberis
#'
#'@seealso
#'[`simpleRandomSampleWithReplacement`]
#'
#'@examples
#'#Set seed for reproducibility
#'set.seed(seed = 5381L)
#'
#'#Take two samples with replacement
#'repeatedSimpleRandomSampleWithReplacement(
#'  k = 2,
#'  N = 10,
#'  n = 6
#')
#'
#'@export
repeatedSimpleRandomSampleWithReplacement <- function(
    k,
    N,
    n
){
  #check input
  isValid = isValidSampleInput(N = N, n = n, prob = NULL, replace = T)
  if(isFALSE(isTRUE(isValid))){
    stop(paste(isValid, collapse = "\n"))
  }
  #compute
  out = repeatedSample(
    k = k,
    sampleFun = simpleRandomSampleWithReplacement,
    N = N,
    n = n
  )
  #return
  return(out)
}

#'Repeated Stratified Random Samples With Replacement
#'
#'@description Takes repeated stratified samples with replacement from the
#'population.
#'See the **Details** section below for further information.
#'
#'@inheritParams repeatedSample
#'@inheritParams stratifiedSampleWithReplacement
#'
#'@inherit repeatedSample return
#'
#'@details This function takes repeated samples by using the \code{\link{replicate}}
#'function and the \code{\link{stratifiedSampleWithReplacement}} sampling
#'function.
#'
#'@author Alessandro Barberis
#'
#'@seealso
#'[`stratifiedSampleWithReplacement`]
#'
#'@examples
#'#Set seed for reproducibility
#'set.seed(seed = 5381L)
#'
#'#Define strata
#'strata = c(rep("a", 3),rep("b", 6))
#'
#'#Check ratio
#'table(strata)/length(strata)
#'
#'#Stratified random samples
#'i = repeatedStratifiedSampleWithReplacement(
#'   k = 2,
#'   strata = strata,
#'   n = 3,
#')
#'#Check ratio
#'table(strata[i[[1]]])/length(strata[i[[1]]])
#'table(strata[i[[2]]])/length(strata[i[[2]]])
#'
#'@export
repeatedStratifiedSampleWithReplacement <- function(
    k,
    strata,
    n,
    prob = NULL
){
  #check input
  isValid = isValidStratifiedSampleInput(strata = strata, n = n, prob = prob, replace = T)
  if(isFALSE(isTRUE(isValid))){
    stop(paste(isValid, collapse = "\n"))
  }
  #compute
  out = repeatedSample(
    k = k,
    sampleFun = stratifiedSampleWithReplacement,
    strata = strata,
    n = n,
    prob = prob
  )
  #return
  return(out)
}


#'Repeated Balanced Random Samples With Replacement
#'
#'@description Takes repeated balanced samples with replacement from the
#'population.
#'See the **Details** section below for further information.
#'
#'@inheritParams repeatedSample
#'@inheritParams balancedSampleWithReplacement
#'
#'@inherit repeatedSample return
#'
#'@details This function takes repeated samples by using the \code{\link{replicate}}
#'function and the \code{\link{balancedSampleWithReplacement}} sampling
#'function.
#'
#'@author Alessandro Barberis
#'
#'@seealso
#'[`balancedSampleWithReplacement`]
#'
#'@examples
#'#Set seed for reproducibility
#'set.seed(seed = 5381L)
#'
#'#Define strata
#'strata = c(rep("a", 3),rep("b", 6))
#'
#'#Check ratio
#'table(strata)/length(strata)
#'
#'#Balanced random samples
#'i = repeatedBalancedSampleWithReplacement(
#'   k = 2,
#'   strata = strata,
#'   n = 6
#')
#'#Check ratio
#'table(strata[i[[1]]])/length(strata[i[[1]]])
#'table(strata[i[[2]]])/length(strata[i[[2]]])
#'
#'@export
repeatedBalancedSampleWithReplacement <- function(
    k,
    strata,
    n,
    prob = NULL
){
  #check input
  isValid = isValidStratifiedSampleInput(strata = strata, n = n, prob = prob, replace = T)
  if(isFALSE(isTRUE(isValid))){
    stop(paste(isValid, collapse = "\n"))
  }
  #compute
  out = repeatedSample(
    k = k,
    sampleFun = balancedSampleWithReplacement,
    strata = strata,
    n = n,
    prob = prob
  )
  #return
  return(out)
}


#'Repeated Bootstrap Samples
#'
#'@description Takes repeated samples with replacement from the population.
#'See the **Details** section below for further information.
#'
#'@inheritParams repeatedSample
#'@inheritParams bootstrapSample
#'
#'@inherit repeatedSample return
#'
#'@details This function takes repeated samples by using the \code{\link{replicate}}
#'function and the \code{\link{bootstrapSample}} sampling
#'function.
#'
#'@author Alessandro Barberis
#'
#'@seealso
#'[`bootstrapSample`]
#'
#'@examples
#'#Set seed for reproducibility
#'set.seed(seed = 5381L)
#'
#'#Take two samples with replacement
#'repeatedBootstrapSample(
#'  k = 2,
#'  N = 10
#')
#'
#'@export
repeatedBootstrapSample <- function(
    k,
    N,
    prob = NULL
){
  #check input
  isValid = isValidSampleInput(N = N, n = N, prob = prob, replace = T)
  if(isFALSE(isTRUE(isValid))){
    stop(paste(isValid, collapse = "\n"))
  }
  #compute
  out = repeatedSample(
    k = k,
    sampleFun = bootstrapSample,
    N = N,
    prob = prob
  )
  #return
  return(out)
}


### Resample k-1 Folds ---------------------------------------------------------

#'Repeated k-1 Random Folds
#'
#'@description Takes repeated samples from the population.
#'See the **Details** section below for further information.
#'
#'@inheritParams randomKFolds
#'
#'@inherit repeatedKm1Folds return
#'
#'@details Each element in the population is randomly assigned to one of the k
#'folds by using the [`randomKFolds`] function.
#'A list of length k is then created from these folds, so that the i-th
#'item of the list is a vector of indices generated by removing the i-th fold
#'and merging the remaining k - 1 folds together.
#'
#'@inherit repeatedKm1Folds author
#'
#'@seealso
#'[`randomKFolds`]
#'
#'@examples
#'#Set seed for reproducibility
#'set.seed(seed = 5381L)
#'
#'#Assign data to 3 folds
#'repeatedRandomKm1Folds(N = 10, k = 3)
#'
#'@export
repeatedRandomKm1Folds <- function(
    k,
    N){
  #get folds
  foldid = randomKFolds(N = N, k = k)
  #get folds as list of k-1 samples
  out = repeatedKm1Folds(foldid = foldid)
  #return
  return(out)
}

#'Repeated k-1 Stratified Folds
#'
#'@description Takes repeated stratified samples from the population.
#'See the **Details** section below for further information.
#'
#'@inheritParams stratifiedKFolds
#'
#'@inherit repeatedKm1Folds return
#'
#'@details Each element in the population is randomly assigned to one of the k
#'folds - so that the percentage of each stratum in the population is preserved
#'in each fold - by using the [`stratifiedKFolds`] function.
#'A list of length k is then created from these folds, so that the i-th
#'item of the list is a vector of indices generated by removing the i-th fold
#'and merging the remaining k - 1 folds together.
#'
#'@inherit repeatedKm1Folds author
#'
#'@seealso
#'[`stratifiedKFolds`]
#'
#'@examples
#'#Set seed for reproducibility
#'set.seed(seed = 5381L)
#'
#'#Define strata
#'strata = c(1,1,1,2,2,2,2,2,2)
#'
#'#Check ratio
#'table(strata)/length(strata)
#'
#'#Assign data to 3 folds
#'i = repeatedStratifiedKm1Folds(
#'  strata = strata,
#'  k = 3
#')
#'#Check indices
#'i
#'#Check ratio in the samples made of k-1 folds
#'table(strata[i[[1]]])/length(strata[i[[1]]])
#'table(strata[i[[2]]])/length(strata[i[[2]]])
#'table(strata[i[[3]]])/length(strata[i[[3]]])
#'
#'@export
repeatedStratifiedKm1Folds <- function(
    k,
    strata){
  #get folds
  foldid = stratifiedKFolds(strata = strata, k = k)
  #get folds as list of k-1 samples
  out = repeatedKm1Folds(foldid = foldid)
  #return
  return(out)
}

#'Repeated k-1 Balanced Folds
#'
#'@description Takes repeated balanced samples from the population.
#'See the **Details** section below for further information.
#'
#'@inheritParams balancedKFolds
#'
#'@inherit repeatedKm1Folds return
#'
#'@details Each element in the population is randomly assigned to one of the k
#'folds so that the percentage of each stratum in the population is balanced
#'in each fold (see [`balancedKFolds`] function for further details).
#'A list of length k is then created from these folds, so that the i-th
#'item of the list is a vector of indices generated by removing the i-th fold
#'and merging the remaining k - 1 folds together.
#'
#'@inherit repeatedKm1Folds author
#'
#'@seealso
#'[`balancedKFolds`]
#'
#'@examples
#'#Set seed for reproducibility
#'set.seed(seed = 5381L)
#'
#'#Define balanced strata
#'strata = c(rep(1,6),rep(2,6))
#'
#'#Check ratio
#'table(strata)/length(strata)
#'
#'#Assign data to 3 folds
#'i = repeatedBalancedKm1Folds(
#'  strata = strata,
#'  k = 3
#')
#'#Check indices
#'i
#'#Check ratio in the samples made of k-1 folds
#'table(strata[i[[1]]])/length(strata[i[[1]]])
#'table(strata[i[[2]]])/length(strata[i[[2]]])
#'table(strata[i[[3]]])/length(strata[i[[3]]])
#'
#'#Define unbalanced strata
#'strata = c(rep(1,6),rep(2,12))
#'
#'#Check ratio
#'table(strata)/length(strata)
#'
#'#Assign data to 3 folds
#'i = repeatedBalancedKm1Folds(
#'  strata = strata,
#'  k = 3,
#'  undersample = TRUE
#')
#'#Check folds
#'i
#'#Check ratio in the samples made of k-1 folds
#'table(strata[i[[1]]])/length(strata[i[[1]]])
#'table(strata[i[[2]]])/length(strata[i[[2]]])
#'table(strata[i[[3]]])/length(strata[i[[3]]])
#'
#'@export
repeatedBalancedKm1Folds <- function(
    k,
    strata,
    undersample = FALSE,
    prob = NULL){
  #get folds
  foldid = balancedKFolds(
    strata = strata,
    k = k,
    undersample = undersample,
    prob = prob)
  #get folds as list of k-1 samples
  out = repeatedKm1Folds(foldid = foldid)
  #return
  return(out)
}

### Resample Leave-P-Out -------------------------------------------------------

#'Repeated Leave-P-Out
#'
#'@description Takes repeated samples from the population.
#'See the **Details** section below for further information.
#'
#'@inheritParams leavePOutSample
#'
#'@return A list of length \eqn{\binom{N}{p}} where each element is a vector
#'containing the indices of the sampled data.
#'
#'@details Samples of size `p` are repeatedly taken from the population until
#'all the possible combinations of `p` elements are considered. These samples
#'are used as holdout data. This function returns a list of
#'\eqn{\binom{N}{p} = \frac{N!}{p!(N-p)!}}
#'samples of size `N-p` obtained by removing the holdout samples from the
#'population.
#'
#'@inherit leavePOutSample author
#'
#'@examples
#'#Set seed for reproducibility
#'set.seed(seed = 5381L)
#'
#'#Repeatedly sample leaving out p elements each time
#'repeatedLeavePOut(N = 5, p = 2)
#'
#'#Equivalent to leave-one-out
#'repeatedLeavePOut(N = 5, p = 1)
#'
#'@export
repeatedLeavePOut <- function(
    N,
    p){
  #get all possible combinations of data to holdout
  holdout = utils::combn(x = seq(N), m = p)
  #coerce as list
  holdout = as.list(x = as.data.frame(x = holdout, optional = T))
  #create output
  ##population
  p = seq(N)
  ##calculate samples
  out = lapply(X = holdout, FUN = setdiff, x = p)
  #return
  return(out)
}


#'Repeated Leave-One-Out
#'
#'@description Takes repeated samples from the population.
#'See the **Details** section below for further information.
#'
#'@inheritParams repeatedLeavePOut
#'
#'@return A list of length `N` where each element is a vector
#'containing the indices of the sampled data.
#'
#'@details The leave-one-out is a particular case of the leave-p-out, where
#'`p = 1`.
#'Samples are repeatedly taken from the population until each element in the
#'population is considered as the holdout data.
#'This function returns a list of `N` samples of size `N-1` obtained by removing
#'the holdout samples from the population.
#'
#'@inherit repeatedLeavePOut author
#'
#'@seealso
#'[`repeatedLeavePOut`]
#'
#'@examples
#'#Set seed for reproducibility
#'set.seed(seed = 5381L)
#'
#'#Assign data to N folds
#'repeatedLeaveOneOut(N = 10)
#'
#'@export
repeatedLeaveOneOut <- function(
    N){
  #get folds
  foldid = randomKFolds(N = N, k = N)
  #get folds as list of k-1 samples
  out = repeatedKm1Folds(foldid = foldid)
  #return
  return(out)
}

# Get Resampling Functions -------------------------------------------------------

#'Get Resampling Function
#'
#'@description This function is a dispatcher for the resampling function selected
#'in input.
#'
#'@param id character string, one of the supported resampling techniques
#'@return A resampling function:
#'
#'\describe{
#' \item{\code{"rswor"               }}{\code{\link{repeatedSampleWithoutReplacement}}}
#' \item{\code{"srswor"              }}{\code{\link{repeatedSimpleRandomSampleWithoutReplacement}}}
#' \item{\code{"stratified_rswor"    }}{\code{\link{repeatedStratifiedSampleWithoutReplacement}}}
#' \item{\code{"balanced_rswor"      }}{\code{\link{repeatedBalancedSampleWithoutReplacement}}}
#' \item{\code{"permutation"         }}{\code{\link{repeatedPermutationSample}}}
#' \item{\code{"kfolds"              }}{\code{\link{repeatedRandomKm1Folds}}}
#' \item{\code{"stratified_kfolds"   }}{\code{\link{repeatedStratifiedKm1Folds}}}
#' \item{\code{"balanced_kfolds"     }}{\code{\link{repeatedBalancedKm1Folds}}}
#' \item{\code{"leave_p_out"         }}{\code{\link{repeatedLeavePOut}}}
#' \item{\code{"leave_one_out"       }}{\code{\link{repeatedLeaveOneOut}}}
#' \item{\code{"rswr"                }}{\code{\link{repeatedSampleWithReplacement}}}
#' \item{\code{"srswr"               }}{\code{\link{repeatedSimpleRandomSampleWithReplacement}}}
#' \item{\code{"stratified_rswr"     }}{\code{\link{repeatedStratifiedSampleWithReplacement}}}
#' \item{\code{"balanced_rswr"       }}{\code{\link{repeatedBalancedSampleWithReplacement}}}
#' \item{\code{"bootstrap"           }}{\code{\link{repeatedBootstrapSample}}}
#'}
#'
#'@author Alessandro Barberis
#'
#'@examples
#'f = getResamplingFunction(id = 'rswor')
#'
#'@export
getResamplingFunction <- function(
    id = c(
      "rswor",
      "srswor",
      "stratified_rswor",
      "balanced_rswor",
      "permutation",
      "kfolds",
      "stratified_kfolds",
      "balanced_kfolds",
      "leave_p_out",
      "leave_one_out",
      "rswr",
      "srswr",
      "stratified_rswr",
      "balanced_rswr",
      "bootstrap"
    )
  ){

  #match arg
  id = match.arg(id)

  #get function
  f = switch(
    id,
    "rswor"                = repeatedSampleWithoutReplacement,
    "srswor"               = repeatedSimpleRandomSampleWithoutReplacement,
    "stratified_rswor"     = repeatedStratifiedSampleWithoutReplacement,
    "balanced_rswor"       = repeatedBalancedSampleWithoutReplacement,
    "permutation"          = repeatedPermutationSample,
    "kfolds"               = repeatedRandomKm1Folds,
    "stratified_kfolds"    = repeatedStratifiedKm1Folds,
    "balanced_kfolds"      = repeatedBalancedKm1Folds,
    "leave_p_out"          = repeatedLeavePOut,
    "leave_one_out"        = repeatedLeaveOneOut,
    "rswr"                 = repeatedSampleWithReplacement,
    "srswr"                = repeatedSimpleRandomSampleWithReplacement,
    "stratified_rswr"      = repeatedStratifiedSampleWithReplacement,
    "balanced_rswr"        = repeatedBalancedSampleWithReplacement,
    "bootstrap"            = repeatedBootstrapSample
  )

  #return
  return(f)
}
